login/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysite/', include('mysite.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include, re_path
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.test import SimpleTestCase, override_settings
from django.conf.urls.static import static


from . import views


app_name = 'mysite'

urlpatterns = [
    path('', views.index, name='index'),

    path('register/', views.register, name='register'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('projects/',views.projectListings,name='projects'),
    path('projectsFiltered/<int:companyId>',views.project_listings,name='projects_filtered'),
    path('profile/',views.profile_fill,name='profile'),
    path('profileUser/',views.profile_fill_user,name='profileUser'),
    path('profileSelection/',views.profile_selection,name='profileSelection'),
    path('showprofile/<int:profileId>',views.show_profile,name='showProfile'),
    path('newProject/',views.newProjectLandingPage,name='newProject'),
    path('projectDisplay/<int:projectId>/',views.projectDisplay,name='projectDisplay'),
    path('issueDisplay/<int:projectId>/<int:bugId>/',views.issueDisplay,name='issueDisplay'),
    path('myIssues/<int:devId>/',views.myIssues,name='myIssue'),
    path('resolveissue/<int:bugId>/',views.resolveIssue,name='resolveIssue'),
    path('vote/<int:postId>/<int:userId>/<int:voteType>/', views.castVote, name='castVote'),
    path('401/',views.E401,name='401'),
    path('404/',views.E404,name='404'),
    path('contact/',views.contact,name='contact'),
    re_path(r'^.*$',views.E404),
]

mysite/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.core.validators import MinValueValidator, MaxValueValidator, EmailValidator, ValidationError

# Create your models here.
class company(models.Model):
    companyName = models.CharField(max_length=50)
    companyId = models.AutoField(primary_key=True)
    companyLogo = models.ImageField(upload_to='company_logo', default='company_logo/buggie.png')

    def __str__(self):
        return self.companyName


class project(models.Model):

    def validateDate(date):
        if datetime.date.today() < date:
            raise ValidationError("Date is in the future")

    project_name = models.CharField(max_length=200)
    projectDescription = models.TextField()
    project_id = models.AutoField(primary_key=True)
    start_date = models.DateField(default=datetime.date.today,validators=[validateDate])
    #end_date = models.DateField()
    company = models.ForeignKey(company, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.project_name




class developer(models.Model):

    PROFILE_CHOICES = (
        ('SS' , 'Senior Software Engineer'),
        ('ST'  , 'Software Tester'),
        ('SA'  , 'Software Architect'),
        ('SE'  , 'Software Engineer'),
        ('SD'  , 'Software Developer'),
	('SY'  , 'Software Analyst'),
	('BA'  , 'Business analyst'),
	('TS'  , 'Technical support'),
    ('US'  , 'User'),
    )

    PROFILE_AUTH_OPTIONS =  (
            ('U', 'user'),
            ('D', 'developer'),
    )
    first_name = models.CharField(max_length=30)
    #middle_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    company = models.ForeignKey(company, on_delete=models.CASCADE)
    profile  = models.CharField(max_length=2,choices=PROFILE_CHOICES)
    #dev_id = models.IntegerField()
    rating = models.FloatField(default=2.5)
    auth_id = models.IntegerField(primary_key=True)
    email = models.CharField(max_length=30)
    username = models.CharField(max_length=20)
    image = models.ImageField(upload_to='profile_image', default='profile_image/person.png')
    profileAuth = models.CharField(max_length=1,choices=PROFILE_AUTH_OPTIONS)
    def __str__(self):
        return self.first_name



class user(models.Model):

    name = models.CharField(max_length=30)
    email = models.CharField(max_length=30,validators=[EmailValidator])
    phone = models.BigIntegerField(validators=[MinValueValidator(7000000000),MaxValueValidator(9999999999)])
    #rating = models.DecimalField(max_digits=5, decimal_places=2, default="")
    auth_id = models.IntegerField(primary_key=True)
    image = models.ImageField(upload_to='profile_image', default='profile_image/person.png')
    rating = models.FloatField(default=2.5)

    def __str__(self):
        return self.name


class bug(models.Model):
    project = models.ForeignKey(project, on_delete=models.CASCADE)
    bug_id = models.AutoField(primary_key=True)
    bug_title = models.CharField(max_length=200)
    bugDescription = models.CharField(max_length=1000)
    BUG_STATUS = (
        ('L' , 'LIVE'),
        ('A' , 'ARCHIVED'),
        ('R' , 'RESOLVED'),
    )
    bug_status = models.CharField(max_length=1,choices=BUG_STATUS)
    bugAssociation = models.ForeignKey(developer,on_delete=models.CASCADE)
    postedOn = models.DateTimeField(default=datetime.datetime.now)
    #userAssociation = models.ForeignKey(developer,on_delete = models.CASCADE)
    def __str__(self):
        return self.bug_title

class post(models.Model):
    bug = models.ForeignKey(bug, on_delete=models.CASCADE)
    postId = models.AutoField(primary_key=True)
    date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(developer, on_delete=models.CASCADE)
    postTitle = models.CharField(max_length=50)
    content = models.CharField(max_length=1000)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return self.bug.project.project_name + ">" + self.bug.bug_title + ">"  + self.postTitle

class contact(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=30,validators=[EmailValidator(message="Enter Valid email", code=None, whitelist=None)])
    phone = models.BigIntegerField(validators=[MinValueValidator(700000000),MaxValueValidator(9999999999)])
    message = models.TextField()

    def __str__(self):
        return self.name

class vote(models.Model):
    VOTE_CHOICES = (
        ('U','Upvote'),
        ('D','Downvote')
    )
    postA = models.ForeignKey(post,on_delete=models.CASCADE)
    userA = models.ForeignKey(developer,on_delete=models.CASCADE)
    voteType = models.CharField(max_length=1,choices=VOTE_CHOICES)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return str(self.userA.username) + " FOR " + str(self.postA) + " TYPE " + str(self.voteType)

mysite/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.validators import MinValueValidator, MaxValueValidator, EmailValidator, ValidationError
from django.views.decorators.cache import never_cache
import smtplib, re

from mysite.forms import DeveloperForm,ProjectForm,BugForm,PostForm,ContactForm,MyUserForm

from mysite.models import developer,user,project,bug,post,company,contact,vote

# Create your views here.


@never_cache
def index(request):
    if request.user.is_authenticated:
        userId = User.objects.get(id=request.user.id)

        try:
            devProfile = developer.objects.get(auth_id=request.user.id)
        except developer.DoesNotExist:
            try:
                userProfile = user.objects.get(auth_id=request.user.id)
            except user.DoesNotExist:
                return render(request, 'mysite/index.html', {'user':request.user})
        return render(request, 'mysite/index.html', {'user':request.user, 'profileFilledAck':request.user})
    else:
        return render(request, 'mysite/index.html')

@never_cache
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('mysite:index'))

@never_cache
def login_(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('mysite:index'))
    try:
        log_in = request.POST['login']
    except MultiValueDictKeyError:
        return render(request, 'mysite/login.html')
    try:
        username = request.POST['username']
        password = request.POST['password']
    except MultiValueDictKeyError:
        error_message = "Missing Credentials"
        return render(request, 'mysite/login.html', {'error_message':error_message})
    user = authenticate(request, username=username,password=password)
    if user is not None:
        login(request, user)
        if not testProfile(user.id):
            return HttpResponseRedirect(reverse('mysite:profileSelection'))
        else:
            return HttpResponseRedirect(reverse('mysite:index'))
    else:
        error_message = "Wrong Credentials"
        return render(request, 'mysite/login.html', {'error_message':error_message})



@never_cache
def register(request):

    errors = []
    #Check if the registeration button has been clicked
    try:
        new_registration = request.POST['register']
    except MultiValueDictKeyError:
        return render(request, 'registration/register.html')

    try:
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password_1']
        confirm_password = request.POST['password_2']
    except MultiValueDictKeyError:
        errors.append("Missing elements in form.")

    if len(errors)==0:
        if password!=confirm_password:
            return render(request, 'registration/register.html', {'passwordError':'Passwords dont match'})
        else:
            validateEmail = EmailValidator()
            try:
                validateEmail(email)
                #validate_myEmail(email)
            except ValidationError:
                return render(request, 'registration/register.html', {'emailError':'Invalid Email'})
            registered = register_user(username,email,password)
            #try to register user




    if len(errors)==0 and registered=='success':
            return HttpResponseRedirect(reverse('mysite:login'))
    else:
        return render(request, 'registration/register.html', {'error_message':errors})



def register_user(usr,mail,passcode):

    print("Trying to register user")
    try:
        test_username = User.objects.get(username=usr)
    except User.DoesNotExist:
        user = User.objects.create_user(usr, mail, passcode)
        user.save()
        return "success"

    return "Username is already registered"

@never_cache
def projectListings(request):

    projects = project.objects.all()
    companies  = company.objects.all()
    #print("here the COmp",companies)
    noIssueProject = {}
    nameProject = {}
    for projectVar in projects:
        noIssueProject[projectVar.project_id] = len(bug.objects.filter(project=projectVar,bug_status='L'))
        nameProject[projectVar.project_id] = projectVar.project_name

    return render(request, 'mysite/project_list.html', {'projects':projects,'cardinal': noIssueProject, 'companies':companies })

@never_cache
def project_listings(request,companyId):

    companies  = company.objects.all()
    projects = project.objects.filter(company__companyId=companyId)
    noIssueProject = {}
    nameProject = {}
    for projectVar in projects:
        noIssueProject[projectVar.project_id] = len(bug.objects.filter(project=projectVar))
        nameProject[projectVar.project_id] = projectVar.project_name

    return render(request, 'mysite/project_list.html', {'projects':projects,'cardinal': noIssueProject, 'companies':companies })

@never_cache
def profile_selection(request):
    if testProfile(request.user.id):
        return HttpResponseRedirect(reverse('mysite:index'))
        
    return render(request,'mysite/profileSelection.html',{'user':user})


@never_cache
def profile_fill(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('mysite:index'))
    if testProfile(request.user.id):
        return HttpResponseRedirect(reverse('mysite:index'))

    builtuserVar = User.objects.get(username=request.user.username)
    builtuserVar.is_staff = True
    builtuserVar.save()
    #print(request.user.username," Is user staff ",request.user.is_staff)
    #if not request.user.is_staff:
    #    return HttpResponseRedirect(reverse('mysite:profileUser'))

    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = DeveloperForm(request.POST,request.FILES)
        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            developerVar = form.save(commit=False)
            developerVar.auth_id = request.user.id
            developerVar.username = request.user.username
            developerVar.email = request.user.email
            developerVar.save()
            #form.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('mysite:showProfile',kwargs={'profileId':request.user.id}))
    # If this is a GET (or any other method) create the default form.
    else:
        form = DeveloperForm()
    return render(request, 'mysite/developers.html', {'form':form})

@never_cache
def show_profile(request,profileId):
    if not testProfile(request.user.id):
        return HttpResponseRedirect(reverse('mysite:404'))

    try:
        devProfile = developer.objects.get(auth_id=profileId)
        devProfile.rating = calcRating(profileId)
        devProfile.save()
    except developer.DoesNotExist:
        try:
            userProfile = user.objects.get(auth_id=profileId)
            userProfile.rating = calcRating(profileId)
            userProfile.save()
        except user.DoesNotExist:
            print("User Not Found")
            return HttpResponseRedirect(reverse('mysite:404'))
        return render(request, 'mysite/profile.html',{'user':request.user,'developer':userProfile})
    return render(request, 'mysite/profile.html',{'user':request.user,'developer':devProfile})

@never_cache
def newProjectLandingPage(request):

    if not testProfile(request.user.id):
        return HttpResponseRedirect(reverse('mysite:index'))

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('mysite:401'))

    userVar = developer.objects.get(auth_id = request.user.id)
    if request.method == 'POST':

        form = ProjectForm(request.POST)
        if form.is_valid():
            ProjectName = form.cleaned_data['project_name']
            ProjectStartDate = form.cleaned_data['start_date']
            ProjectCompany = userVar.company

            ProjectVar = project.objects.create(project_name=ProjectName,start_date=ProjectStartDate,company=ProjectCompany)
            ProjectVar.save()
            #ProjectVar = form.save(commit=False)
            # Make edits
            #ProjectVar.save()

            return HttpResponseRedirect(reverse('mysite:projects'))
    else:
        form = ProjectForm()

    return render(request, 'projects/landing.html', {'form':form})


# Individual Projects page to see issues already registered and also a form to create a new Issue
@never_cache
def projectDisplay(request,projectId):

    if not testProfile(request.user.id):
        return HttpResponseRedirect(reverse('mysite:index'))

    projectVar = project.objects.get(project_id=projectId)
    issuesVar = bug.objects.filter(project__project_id=projectId)
    liveIssuesVar = bug.objects.filter(project__project_id=projectId,bug_status='L')

    if request.method == 'POST':
        form = BugForm(request.POST)
        if form.is_valid():
            bugTitle = form.cleaned_data['bug_title']
            bugDescription = form.cleaned_data['bugDescription']
            projectAssociation = project.objects.get(project_id = projectId)
            bugStatus = 'L'
            userVar = developer.objects.get(auth_id = request.user.id)
            bugVar = bug.objects.create(bug_title=bugTitle, bugDescription=bugDescription, project=projectAssociation, bug_status=bugStatus, bugAssociation=userVar)
            bugVar.save()

            return HttpResponseRedirect(reverse('mysite:projectDisplay',kwargs={'projectId':projectId} ))

    else:

mysite/templates/mysite/401.html
<!DOCTYPE HTML>
<html>
<head>
    <title>401</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mysite/style401.css' %}">
</head>
<body>
  <div class="page-wrap">
    <h1>401</h1>
    <h2>unauthorized</h2>
    <p>Well, what to say. Hmm? Sorry ...</p>
    <p><a href="{% url 'mysite:index' %}">home</a></p>
  </div>
</body>
</html>

mysite/templates/mysite/contact.html
{% extends 'base.html' %}
{% block head %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'mysite/contactStyle.css' %}">
{% endblock %}
{% block body %}


<div class="container">
  <form id="contact" action="{%url 'mysite:contact' %}" method="post">
    {%csrf_token%}
    <h3>Our Contact Form</h3>
    <h4>Contact us for get Your Company Registered</h4>

    {% for field in form %}
    <fieldset>
      {{field.errors}}
      <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{field.label}}</label>
      {{field}}
      {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
      {% endif %}
    </fieldset>
    {%endfor%}
    <input type="submit" value="Submit">
  </form>
</div>


{% endblock %}

mysite/templates/mysite/developersUser.html
{% extends 'base.html' %}

{% block body %}


<div class='container'>

            <form class="form-horizontal" action="{% url 'mysite:profileUser' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}


                {% for field in form %}
                <div class="form-group">
                  <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{field.label}}</label>

                  <div class="col-sm-10">
                    {{ field }} {{field.errors}}
                  </div>
                </div>
                {%endfor%}


                <input type="submit" value="Submit">
            </form>

</div>

{% endblock %}

mysite/templates/mysite/index.html
  {% extends 'base.html' %}
{%block head%}
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,500" rel="stylesheet">

{%endblock%}
  {% block body %}


      <div class = "container-index container">
        {%load static%}
        <div class="jumbotron jumbotron-fluid" style="background-image:url({% static 'mysite/buggie.png'%});height:400px">
            <div class="container">
          <h1 class="display-4" style='text-align:left'>BUGGIE</h1>
              <p class="lead" style='text-align:left'>This is a Issue Tracking system.</p>
          </div>
        </div>
        {% if not user.is_authenticated %}
        <a href="{% url 'mysite:login' %}"><button class='btn btn-default'>Click here to Login</button></a> {{ profileFilledAck }}
        <a href="{% url 'mysite:register' %}"><button class='btn btn-default'>Click here to Register</button></a><br>
        {% endif %}
        {% if user.is_authenticated %}
        {% if not profileFilledAck %}
          <span class = 'profileFilledAck'>You have not filled your Profile details</span>
          <a href="{% url 'mysite:profileSelection' %}"><button class='btn btn-default'>Click here to Fill your profile</button></a><br>
        {% endif %}
        {% endif %}

        <!--  <a href="{% url 'mysite:logout' %}">Click here to Logout</a>-->




      </div>
  {% endblock %}

mysite/templates/mysite/issue.html
{% extends 'base.html' %}
{%block head%}

{%endblock%}
{% block body %}

  <div class='container'>

    <h3 class='public'>
      <svg class="octicon octicon-repo" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9H3V8h1v1zm0-3H3v1h1V6zm0-2H3v1h1V4zm0-2H3v1h1V2zm8-1v12c0 .55-.45 1-1 1H6v2l-1.5-1.5L3 16v-2H1c-.55 0-1-.45-1-1V1c0-.55.45-1 1-1h10c.55 0 1 .45 1 1zm-1 10H1v2h2v-1h3v1h5v-2zm0-10H2v9h9V1z"></path></svg>
      <span class='author'> {{company.companyName}} </span> <span class="path-divider">/</span> <span class='name'> {{project.project_name}} </span>
    </h3>
    <hr>

    <div class="created-by" style="float:inherit">
      <span>Posted By : </span>
      <img class="rounded-circle account-img" src="{{ postedBy.image.url }}" alt="Image" width='30px' >
      <a href="{% url 'mysite:showProfile' postedBy.auth_id %}">{{postedBy.username}}</a>
    </div>
    <hr>
    <div class='bug-title'>
        <span style="font-size:24px">{{ issue.bug_title }}</span>
        {% if issue.bug_status == 'L'%}
        <span class="badge badge-pill badge-danger" style='color:white;background-color:#DC143C;'>Live</span>
        {% endif %}
        {% if issue.bug_status == 'R'%}
        <span class="badge badge-pill badge-info" styel='color:white;background-color:#008B8B;'>Resolved</span>
        {% endif %}
    </div>

    <div class='bug-desc'>
      <span> {{ issue.bugDescription }} </span>
    </div>



    <ul>
    {% for post in posts %}

    <div class="card-post" style="width:100%">

        <div class="card-header-post">
            <img class="rounded-circle account-img" src="{{ post.user.image.url }}" alt="Image" width='30px' >
          <a href="{% url 'mysite:showProfile' post.user.auth_id %}">  {{post.user.username}} </span> </a>
        </div>
        <div class="card-body-post">
          <h4 class="card-title-post" sytle="color:red;">{{post.postTitle}}</h5>
          <hr>
          <p class="card-text-post">{{post.content}}</p>
          <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        {%load static%}
          <a href="{%url 'mysite:castVote' post.postId request.user.id 1%}"><img src="{%static 'mysite/icon-like.png'%}" width=20px></a>
          <span class='count-like'>{{post.upvotes}}</span>
          <a href="{%url 'mysite:castVote' post.postId request.user.id 2%}"><img src="{%static 'mysite/icon-dislike.png'%}" width=20px></a>
          <span class='count-dislike'>{{post.downvotes}}</span>

    </div>

    {% endfor  %}
  </ul>

{% if issue.bug_status == 'L'%}
  <div class='form'>

    <form class="form-horizontal" action="{% url 'mysite:issueDisplay' project.project_id issue.bug_id %}" method="post" >
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group" style="padding-bottom:14px">
                  <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{field.label}}</label>
                  <div class="col-sm-10">
                    {{ field }}
                  </div>
                </div>
                {%endfor%}
               <button type="submit" class="btn btn-primary mb-2" style="width:200px">Post</button>
            </form>

  </div>
{%endif%}

  </div>


{% endblock %}

mysite/templates/mysite/myissues.html
{%extends 'base.html'%}

{%block body%}

  <div class="container" style="padding-top:20px">

    <div class="alert alert-info" role="alert">
      Issues posted by  @<a href="{%url 'mysite:showProfile' developer.auth_id %}">{{developer.username}}</a> &nbsp <img class="rounded-circle account-img" src="{{developer.image.url}}" width=20px>
    </div>



      		<div class='margins' style="padding:40px">
      			<table class='table table-striped table-bordered'>
      				<tr>
      					<th>Issue Title</th>
      					<th>Project</th>
      					<th>Company</th>
      					<th>Posted On</th>
                <th>Status</th>
                <th>Toggle Status</th>
      				</tr>
              {%load static%}
      				{% for issue in issues %}

      					<tr>
      						<th> <a href="{% url 'mysite:issueDisplay' issue.project.project_id issue.bug_id %}"> {{ issue.bug_title }} </a> </th>
      						<th> {{issue.project.project_name}} </th>
      						<th> {{issue.project.company.companyName}} </th>
      						<th> {{ issue.postedOn }} </th>
                  <th {% if issue.bug_status == 'L' %}
                        style="background-color:red"
                        {%endif%}
                        {% if issue.bug_status == 'R' %}
                              style="background-color:#008B8B"
                              {%endif%}>{{issue.bug_status}}</th>
                  <th style="text-align:center"><a href="{%url 'mysite:resolveIssue' issue.bug_id%}"><img src="{%static 'mysite/check-mark.png'%}"width=40px></a></th>
      					</tr>

      				{% endfor %}
      			</table>
      		</div>


  </div>

{%endblock%}

mysite/templates/mysite/profile.html
{%extends 'base.html'%}
{% block body %}
{%load static%}
        <div class="container">


         {% if error_message %} <p><strong> {{ error_message }} </strong></p>{% endif %}


            <div class="card">
                  <img class="rounded-circle account-img" src="{{ developer.image.url }}" alt="Image" width='300px'>
                  <h1>{{developer.first_name}} {{developer.last_name}} {{developer.name}}</h1>

                  <p class="title">{{ developer.get_profile_display }} </p>
                  <p><img src="{{developer.company.companyLogo.url}}" width="40px">&nbsp{{ developer.company }}</p>
                  <p><button class="profileContactButton" id='btnContact'>Contact</button></p>
                  <p><a href="{% url 'mysite:myIssue' developer.auth_id%}">Issues</a></p>
                  <p style="text-align:center">Rating</p>
                  <div class="progress">
                    {%load mysite_extras%}
                      <div class="progress-bar" role="progressbar" style="width:{{developer.rating|mul}}%;" aria-valuenow="" aria-valuemin="0" aria-valuemax="5">{{developer.rating}}</div>
                  </div>
          </div>

        </div>

        <div id="myModal" class="modal" style="margin:200px">
            <!-- Modal content -->
            <div class="modal-content">
              <span class="close">&times;</span>
              <p>{{ developer.email }}</p>
            </div>
        </div>

        <script>
        var modal = document.getElementById('myModal');

        // Get the button that opens the modal
        var btn = document.getElementById("btnContact");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks on the button, open the modal
        btn.onclick = function() {
        modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
        modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
              modal.style.display = "none";
            }
        }
</script>
{% endblock %}

mysite/templates/mysite/profileSelection.html
{% extends 'base.html' %}

{% block body %}

  <div class='container' style="padding-top:20px">

      <a href="{% url 'mysite:profile' %}"><button class='selection'>Click here to register for a Developer profile</button></a>
      <a href="{% url 'mysite:profileUser' %}"><button class='selection'>Click here to register for a User profile</button></a>

  </div>

{% endblock %}

mysite/templates/mysite/projectPage.html
{% extends 'base.html' %}

{%block head%}
<style>
.list-group li.live-bug{
  background-color:red;
}
</style>
{%endblock%}
{% block body %}

<div class='container' style="padding:10px">

  <div class="jumbotron" style="padding:20px">
    <h2 class='public'>
      <img src="{{project.company.companyLogo.url}}" width=30px>
      <span class='author'> {{project.company.companyName}} </span> <span class="path-divider">/</span> <span class='name'> {{project.project_name}} </span>
    </h2>
    <hr class="my-4">
  <p class="lead" style="text-align: justify;
  text-justify: inter-word;">{{ project.projectDescription }}</p>


  <!--<p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>-->
  </div>
  <hr>

  <p> Add new Issue Form </p>


  <div class='form'>
    <form class="form-horizontal" action="{% url 'mysite:projectDisplay' project.project_id %}" method="post" style="padding:5px" >
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                  <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{field.label}}</label>
                  <div class="col-sm-10">
                    {{ field }}
                  </div>
                </div>
                {%endfor%}

                  <br><input type="submit" value="Submit">
            </form>
  </div>


  <span class='project-info'>Number of active issues : {{ numberOfIssues }} </span>
  <div class='project-issues' styel="padding:10px">
    <table class='table table-striped table-bordered'>
      <tr>
        <th>Bug</th>
        <th>Posted By</th>
        <th>Posteed on</th>
        <th>Status</th>
      </tr>
      {% for issue in issues %}
      <tr>
        <th><a href="{% url 'mysite:issueDisplay' project.project_id issue.bug_id %}"> {{ issue.bug_title }} </a></th>
        <th><a href="{% url 'mysite:showProfile' issue.bugAssociation.auth_id %}">{{issue.bugAssociation.username}}</a></th>
        <th>{{issue.postedOn}}</th>
        <th {% if issue.bug_status == 'L' %}
              style="background-color:red"
              {%endif%}
              {% if issue.bug_status == 'R' %}
                    style="background-color:#008B8B"
                    {%endif%}>{{issue.bug_status}}</th>
      </tr>
      {%endfor%}
    </table>
  </div>


{% endblock %}